spring:
  application:
    name: enterProject
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 4865
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
